# Generated by Django 4.2.6 on 2023-10-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
